/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLayoutRouteImport } from './routes/auth/_layout'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as AuthLayoutLoginRouteImport } from './routes/auth/_layout.login'
import { Route as AuthLayoutAdminregisterRouteImport } from './routes/auth/_layout.adminregister'
import { Route as AuthLayoutAdminloginRouteImport } from './routes/auth/_layout.adminlogin'
import { Route as AdminLayoutDashboardRouteImport } from './routes/admin/_layout.dashboard'

const AuthRouteImport = createFileRoute('/auth')()
const AdminRouteImport = createFileRoute('/admin')()

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthRoute,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AdminRoute,
} as any)
const AuthLayoutLoginRoute = AuthLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutAdminregisterRoute = AuthLayoutAdminregisterRouteImport.update({
  id: '/adminregister',
  path: '/adminregister',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutAdminloginRoute = AuthLayoutAdminloginRouteImport.update({
  id: '/adminlogin',
  path: '/adminlogin',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AdminLayoutDashboardRoute = AdminLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/auth': typeof AuthLayoutRouteWithChildren
  '/admin/dashboard': typeof AdminLayoutDashboardRoute
  '/auth/adminlogin': typeof AuthLayoutAdminloginRoute
  '/auth/adminregister': typeof AuthLayoutAdminregisterRoute
  '/auth/login': typeof AuthLayoutLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/auth': typeof AuthLayoutRouteWithChildren
  '/admin/dashboard': typeof AdminLayoutDashboardRoute
  '/auth/adminlogin': typeof AuthLayoutAdminloginRoute
  '/auth/adminregister': typeof AuthLayoutAdminregisterRoute
  '/auth/login': typeof AuthLayoutLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth/_layout': typeof AuthLayoutRouteWithChildren
  '/admin/_layout/dashboard': typeof AdminLayoutDashboardRoute
  '/auth/_layout/adminlogin': typeof AuthLayoutAdminloginRoute
  '/auth/_layout/adminregister': typeof AuthLayoutAdminregisterRoute
  '/auth/_layout/login': typeof AuthLayoutLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/dashboard'
    | '/auth/adminlogin'
    | '/auth/adminregister'
    | '/auth/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/dashboard'
    | '/auth/adminlogin'
    | '/auth/adminregister'
    | '/auth/login'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/_layout'
    | '/auth'
    | '/auth/_layout'
    | '/admin/_layout/dashboard'
    | '/auth/_layout/adminlogin'
    | '/auth/_layout/adminregister'
    | '/auth/_layout/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/_layout': {
      id: '/auth/_layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/_layout/login': {
      id: '/auth/_layout/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLayoutLoginRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/_layout/adminregister': {
      id: '/auth/_layout/adminregister'
      path: '/adminregister'
      fullPath: '/auth/adminregister'
      preLoaderRoute: typeof AuthLayoutAdminregisterRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/_layout/adminlogin': {
      id: '/auth/_layout/adminlogin'
      path: '/adminlogin'
      fullPath: '/auth/adminlogin'
      preLoaderRoute: typeof AuthLayoutAdminloginRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/admin/_layout/dashboard': {
      id: '/admin/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminLayoutDashboardRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface AdminLayoutRouteChildren {
  AdminLayoutDashboardRoute: typeof AdminLayoutDashboardRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutDashboardRoute: AdminLayoutDashboardRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface AdminRouteChildren {
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthLayoutRouteChildren {
  AuthLayoutAdminloginRoute: typeof AuthLayoutAdminloginRoute
  AuthLayoutAdminregisterRoute: typeof AuthLayoutAdminregisterRoute
  AuthLayoutLoginRoute: typeof AuthLayoutLoginRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutAdminloginRoute: AuthLayoutAdminloginRoute,
  AuthLayoutAdminregisterRoute: AuthLayoutAdminregisterRoute,
  AuthLayoutLoginRoute: AuthLayoutLoginRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface AuthRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
